### ISSUE TITLE
Outdated AWS java sdk causes problems

### ISSUE THREAD

**Issue by ThomasBergman1** [indeedeng/imhotep#28]
Dependencies are outdated:

There's an issue with aws java SDK that imhotep uses
basically the same issue as here: https://github.com/soabase/exhibitor/issues/213

imhotepDaemon fails to start with the same error if I point it to s3 bucket in Frankfurt, but work for Ireland or other aws regions

    Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: XXX), S3 Extended Request ID: XXX
    	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:820)
    	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:439)
    	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:245)
    	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3722)
    	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3675)
    	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:620)
    	at com.indeed.imhotep.io.caching.S3RemoteFileSystem.getListing(S3RemoteFileSystem.java:160)
    	at com.indeed.imhotep.io.caching.S3RemoteFileSystem.stat(S3RemoteFileSystem.java:176)
    	at com.indeed.imhotep.io.caching.SqarAutomountingRemoteFileSystem.stat(SqarAutomountingRemoteFileSystem.java:126)
    	at com.indeed.imhotep.io.caching.RemappingRemoteFileSystem.stat(RemappingRemoteFileSystem.java:66)
    	at com.indeed.imhotep.io.caching.CachedRemoteFileSystem.stat(CachedRemoteFileSystem.java:149)
    	at com.indeed.imhotep.io.caching.CachedFile.exists(CachedFile.java:85)
    	at com.indeed.imhotep.service.CachingLocalImhotepServiceCore.updateShards(CachingLocalImhotepServiceCore.java:245)
    	at com.indeed.imhotep.service.CachingLocalImhotepServiceCore.<init>(CachingLocalImhotepServiceCore.java:148)
    	at com.indeed.imhotep.service.ImhotepDaemon.newImhotepDaemon(ImhotepDaemon.java:758)
    	at com.indeed.imhotep.service.ImhotepDaemon.main(ImhotepDaemon.java:728)
    	at com.indeed.imhotep.service.ImhotepDaemon.main(ImhotepDaemon.java:694)

Imhotep is using 1.7.14, and according to the dude in this github issue it's fixed in atleast 1.9.16 which was in 2015. Current version is 1.11.262

**Comment by youknowjack** [comment]
I have upgraded aws-java-sdk and related jackson libraries, fixed resulting bugs, and done a basic round of testing -- in imhotep-server as well as https://github.com/indeedeng/iql and https://github.com/indeedeng/iupload. The snapshot binaries in S3 should now work for you, please let us know if you run into further issues.
